# Generated by Django 4.1.7 on 2023-08-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlenew',
            old_name='profile_photo',
            new_name='photo',
        ),
    ]
