# Generated by Django 4.1.7 on 2023-07-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='company',
            name='num_employees',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
