# Generated by Django 4.1.7 on 2023-07-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_alter_vacancy_options_vacancy_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['salary'], 'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterUniqueTogether(
            name='vacancy',
            unique_together={('title', 'email')},
        ),
    ]
