# Generated by Django 4.1.7 on 2023-07-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_resume_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo/', verbose_name='ФОТО сотрудника'),
        ),
    ]
